# parameter for the CNN autoencoder
learning_rate: 0.00015
weight_decay: 0.000
batch_size: 512
n_epochs: 1500

encoded_space_dim: 50
fc2_input_dim: 256

# clustering_algorithm
clustering_algo: "agg"
n_clusters: 4

# for mask optimization
n_iter_mask_optimization: 250 # 250 normally
learning_rate_mask_optimization: 0.05 # 0.05 normally

# for supervised learning using the angle (path optimization)
n_iter_supervised_learning: 150 # 100 normally
learning_rate_supervised_learning: 0.002 # 0.002 normally

# for the evolution strategies
es_sigma: 0.01
es_lr: 0.0001
es_pop_size: 100
es_epochs: 1
n_params_to_perturb: 19126

# session name
session_name: "session_1"
