# parameter for the CNN autoencoder
learning_rate: 0.0002
weight_decay: 0.000
batch_size: 512
n_epochs: 1000

encoded_space_dim: 50
fc2_input_dim: 256

# clustering_algorithm
clustering_algo: "kmeans"
n_clusters: 4

# for mask optimization
n_iter_mask_optimization: 250
learning_rate_mask_optimization: 0.05

# for supervised learning using the angle
n_iter_supervised_learning: 50
learning_rate_supervised_learning: 0.0015

# for the evolution strategies
es_sigma: 0.01
es_lr: 0.0001
es_pop_size: 100
es_epochs: 10

# session name
session_name: "session_1"
