scenarios:
  - 2
  - 3
  - 4
  - 5
  - 8
  - 12
  - 24
  - 25
  - 27
  - 29

best_scenario_radius:
  - 3
  - 3
  - 3
  - 3
  - 3
  - 3
  - 3
  - 3
  - 3
  - 3

best_scenario_arc:
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0

