radius_dictionary:
#  2: 4
#  3: 4
#  4: 6
  5: 5
#  8: 6
  12: 5
#  24: 6
#  25: 6
#  27: 6
#  29: 6
  
arc_dictionary:
#  2: 0
#  3: 0
#  4: 0
  5: 0
#  8: 0
  12: 0
#  24: 0
#  25: 0
#  27: 0
#  29: 0

